Update git submodules
* Update skins/Vector from branch 'wmf/1.41.0-wmf.5'
  to 8d533aa7e7f8468447e5b0f8d0ba35dfbdf2fcdf
  - Fix TypeError: trigger.attr is not a function
    
    Code was assuming jQuery.Object when it is now an Element.
    
    Bug: T335148
    Change-Id: I4755607f991889468294e022015a6a7e4becbb6c
    (cherry picked from commit c61d57c72afb0166212d552d46b937e0642d5319)